### ISSUE TITLE
Fix footer buttons.

### ISSUE THREAD

**Issue by McWashr** [Jamal135/135Project#3]
Currently the middle settings button will not be perfectly center unless the left and right buttons are of equal length. The cheat short term fix for this by padding the right button with blank characters is not ideal and results in broken underlining when actively hovered over. This likely requires flex or otherwise some HTML work on footer.html

**Comment by Jamal135** [comment]
Issue fixed in latest commit.
`html
        <div class="justify-content-between d-flex">
            <a class="btn btn-block btn-link text-grey text-left" href="/disclaimer">Disclaimer</a>
            <a class="btn btn-block btn-link text-grey text-center" href="/settings">Settings</a>
            <a class="btn btn-block btn-link text-grey text-right" href="/privacy">Privacy</a>
        </div>
`

**Comment by McWashr** [comment]
Fixed in latest commit.
